### ISSUE TITLE
Research: Elastic Search [S]

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/document-cache#7]
- [ ] Determine best solution for searching the DHO.
- [ ] Be able to search any text within the different properties of the documents

**Comment by sebastianmontero** [comment]
Elastic search would enable us to:

- Stream documents in JSON format into it for storage
- Stored documents would be indexed for fast retrieval
- The elastic search API would allow us to search documents by a specific property or all properties

### **Infrastructure**

**Cloud offering:**

Fully manged software as a service

Pricing:

![image](https://user-images.githubusercontent.com/13155714/148827458-507c2e78-af40-4488-beee-5174cc399937.png)

**Self Managed:**

Elasticsearch basic version software is free, which would allow us to run elasticsearch on our own infrastructure. 

There are no clear guidelines provided in terms of infrastructure requirements as they are dependant on the application, would need to perform some tests to determine optimal hardware.
